"""initial schema

Revision ID: 8fd75e8a0d7b
Revises: 
Create Date: 2026-02-17 23:37:15.413498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd75e8a0d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos_series_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.Column('cada_n_semanas', sa.Integer(), nullable=False),
    sa.Column('patrones_json', sa.JSON(), nullable=False),
    sa.Column('total_intentados', sa.Integer(), nullable=False),
    sa.Column('total_creados', sa.Integer(), nullable=False),
    sa.Column('total_fallidos', sa.Integer(), nullable=False),
    sa.Column('fallidos_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turnos_series_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_series_log_serie_id'), ['serie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turnos_series_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos_series_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnos_series_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_turnos_series_log_serie_id'))

    op.drop_table('turnos_series_log')
    # ### end Alembic commands ###
